version: 2

models:
  - name: severity_by_demographics
    description: "Analysis of cancer severity distribution across different demographic groups"
    columns:
      - name: analysis_type
        description: "Type of analysis (age_gender_distribution or age_range_severity)"
        tests:
          - not_null

  - name: risk_factor_analysis
    description: "Analysis of risk factors and their correlation with cancer severity"
    columns:
      - name: risk_factor
        description: "Name of the risk factor being analyzed"
        tests:
          - not_null

      - name: correlation_strength
        description: "Strength of correlation between risk factor and high severity"
        tests:
          - not_null

  - name: symptom_correlation
    description: "Analysis of symptoms and their correlation with cancer severity levels"
    columns:
      - name: symptom
        description: "Name of the symptom being analyzed"
        tests:
          - not_null

      - name: symptom_category
        description: "Category of symptom (Critical/Major/Supporting)"
        tests:
          - not_null
          - accepted_values:
              values: ['Critical', 'Major', 'Supporting']

      - name: correlation_rank
        description: "Rank of symptom by correlation strength"
        tests:
          - not_null